name: Generate Qatar1 EPG

on:
  schedule:
    - cron: '0 3 * * *'  # يتم التشغيل تلقائياً كل يوم الساعة 3 صباحاً بتوقيت UTC
  workflow_dispatch:      # يتيح تشغيل المهمة يدوياً من واجهة GitHub

jobs:
  build:
    name: Run EPG Script
    runs-on: ubuntu-latest

    steps:
    - name: سحب ملفات المستودع
      uses: actions/checkout@v3

    - name: تجهيز بيئة Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: تثبيت المكتبات المطلوبة
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: تشغيل سكربت توليد الـ EPG
      run: python generate_epg.py

    - name: حفظ التغييرات في المستودع
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        touch qatar1.xml  # تأكد من أن الملف يظهر في Git
        git add qatar1.xml providers.json || true
        git commit -m "Auto-update EPG file" || echo "No changes to commit"
        git push
      continue-on-error: true
